apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: register-app
  template:
    metadata:
      labels:
        app: register-app
    spec:
      containers:
      - name: register-app
        image: 120695692422.dkr.ecr.us-east-1.amazonaws.com/register-app:1.0
        ports:
        - containerPort: 80
